#!/bin/sh

. /config.sh

export PATH=/bin
mount proc /proc -t proc
mount sys /sys -t sysfs
mount devtmpfs /dev -t devtmpfs
mount debugfs /sys/kernel/debug -t debugfs
mount tracefs /sys/kernel/debug/tracing -t tracefs
mkdir /dev/pts
mount devpts /dev/pts -t devpts
ln -s /bin /usr/bin
ln -s /proc/self/fd /dev/fd
ip link set eth0 down
ip link add br0 type bridge
ip link set eth0 master br0
ip link set eth0 up
ip link set br0 up
udhcpc -i br0 -s ./dhcp-client-script.sh
mkdir /host
mount -t 9p -o trans=virtio host /host -oversion=9p2000.L,msize=16777216
telnetd -p $HOST_TELNET_PORT
adduser tcpdump -p tcpdump
